// Golden-value tests for the DockLayout.js `layout()` port plus unit tests
// for the amplitude envelope contract and the DockModel.js `reconcile()` port.
//
// The truth table below was generated by running the original
// DockLayout.js:18-58 `layout()` under Node (truths.jsonl, 21 scenarios).
// `pointer` serialises NaN/Infinity as null — restored per scenario name
// (C_nan → double.nan, D_inf → double.infinity). Scenario "B" is a deprecated
// placeholder superseded by B1..B4 and is skipped.

import 'dart:convert';
import 'dart:math' as math;

import 'package:kos_dock/src/layout/dock_magnifier.dart';
import 'package:test/test.dart';

const _truthsJsonl = r'''
{"name":"A","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":400,"sectionBoundary":[],"strength":1,"size":48,"baseLength":336,"length":343.51651946486356,"divider":-1,"dividers":[],"overflow":false,"slots":[{"center":40,"start":12,"span":56.00000004077454,"size":48.00000004077454},{"center":96,"start":68.00000004077454,"span":56.00001531563405,"size":48.00001531563405},{"center":140,"start":124.0000153564086,"span":32.00040035818644,"size":48.00080071637288},{"center":184,"start":156.00041571459502,"span":56.022579382889134,"size":48.022579382889134},{"center":240,"start":212.02299509748417,"span":56.648187551313534,"size":48.648187551313534},{"center":296,"start":268.6711826487977,"span":62.84533681606584,"size":54.84533681606584}]}
{"name":"B","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":0,"sectionBoundary":[3],"strength":1,"size":48,"baseLength":360,"length":399.4712466628437,"divider":207.43189227604844,"dividers":[207.43189227604844],"overflow":false,"slots":[{"center":40,"start":12,"span":85.75375726911678,"size":77.75375726911678},{"center":96,"start":97.75375726911678,"span":64.83454588136226,"size":56.83454588136227},{"center":140,"start":162.58830315047902,"span":32.84358912556942,"size":49.687178251138846},{"center":208,"start":219.43189227604844,"span":56.03877801858993,"size":48.03877801858993},{"center":264,"start":275.47067029463835,"span":56.00057325068667,"size":48.00057325068667},{"center":320,"start":331.471243545325,"span":56.00000311751872,"size":48.00000311751872}]}
{"name":"B1_center","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":96,"sectionBoundary":[3],"strength":1,"size":48,"baseLength":360,"length":441.4279938412347,"divider":243.7916517329688,"dividers":[243.7916517329688],"overflow":false,"slots":[{"center":40,"start":12,"span":79.29077733296512,"size":71.29077733296512},{"center":96,"start":91.29077733296512,"span":94.4,"size":86.4},{"center":140,"start":185.69077733296513,"span":46.10087440000368,"size":76.20174880000737},{"center":208,"start":255.7916517329688,"span":61.19687487628593,"size":53.19687487628593},{"center":264,"start":316.98852660925473,"span":56.426585467068506,"size":48.426585467068506},{"center":320,"start":373.4151120763232,"span":56.012881764911455,"size":48.012881764911455}]}
{"name":"B2_plus1","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":152,"sectionBoundary":[3],"strength":1,"size":48,"baseLength":360,"length":436.1660954443286,"divider":215.25185776800902,"dividers":[215.25185776800902],"overflow":false,"slots":[{"center":40,"start":12,"span":61.19687487628593,"size":53.19687487628593},{"center":96,"start":73.19687487628593,"span":79.29077733296512,"size":71.29077733296512},{"center":140,"start":152.48765220925105,"span":50.76420555875798,"size":85.52841111751596},{"center":208,"start":227.25185776800902,"span":79.29077733296512,"size":71.29077733296512},{"center":264,"start":306.54263510097417,"span":61.19687487628593,"size":53.19687487628593},{"center":320,"start":367.7395099772601,"span":56.426585467068506,"size":48.426585467068506}]}
{"name":"B3_plus2","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":208,"sectionBoundary":[3],"strength":1,"size":48,"baseLength":360,"length":441.69697288210773,"divider":182.80932067285664,"dividers":[182.80932067285664],"overflow":false,"slots":[{"center":40,"start":12,"span":56.426585467068506,"size":48.426585467068506},{"center":96,"start":68.4265854670685,"span":61.19687487628593,"size":53.19687487628593},{"center":140,"start":129.62346034335445,"span":41.18586032950219,"size":66.37172065900438},{"center":208,"start":194.80932067285664,"span":94.4,"size":86.4},{"center":264,"start":289.2093206728566,"span":79.29077733296512,"size":71.29077733296512},{"center":320,"start":368.50009800582177,"span":61.19687487628593,"size":53.19687487628593}]}
{"name":"B4_minus1","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":40,"sectionBoundary":[3],"strength":1,"size":48,"baseLength":360,"length":426.02861735644876,"divider":233.58900702098697,"dividers":[233.58900702098697],"overflow":false,"slots":[{"center":40,"start":12,"span":94.4,"size":86.4},{"center":96,"start":106.4,"span":79.29077733296512,"size":71.29077733296512},{"center":140,"start":185.69077733296513,"span":35.89822968802185,"size":55.7964593760437},{"center":208,"start":245.58900702098697,"span":56.426585467068506,"size":48.426585467068506},{"center":264,"start":302.01559248805546,"span":56.012881764911455,"size":48.012881764911455},{"center":320,"start":358.02847425296693,"span":56.00014310348181,"size":48.00014310348181}]}
{"name":"C_nan","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":null,"sectionBoundary":[3],"strength":1,"size":48,"baseLength":360,"length":360,"divider":168,"dividers":[168],"overflow":false,"slots":[{"center":40,"start":12,"span":56,"size":48},{"center":96,"start":68,"span":56,"size":48},{"center":140,"start":124,"span":32,"size":48},{"center":208,"start":180,"span":56,"size":48},{"center":264,"start":236,"span":56,"size":48},{"center":320,"start":292,"span":56,"size":48}]}
{"name":"D_inf","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":null,"sectionBoundary":[3],"strength":1,"size":48,"baseLength":360,"length":360,"divider":168,"dividers":[168],"overflow":false,"slots":[{"center":40,"start":12,"span":56,"size":48},{"center":96,"start":68,"span":56,"size":48},{"center":140,"start":124,"span":32,"size":48},{"center":208,"start":180,"span":56,"size":48},{"center":264,"start":236,"span":56,"size":48},{"center":320,"start":292,"span":56,"size":48}]}
{"name":"E_half","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":400,"sectionBoundary":[],"strength":0.5,"size":48,"baseLength":336,"length":339.7582597324317,"divider":-1,"dividers":[],"overflow":false,"slots":[{"center":40,"start":12,"span":56.000000020387276,"size":48.000000020387276},{"center":96,"start":68.00000002038728,"span":56.00000765781702,"size":48.00000765781702},{"center":140,"start":124.0000076782043,"span":32.00020017909321,"size":48.00040035818643},{"center":184,"start":156.0002078572975,"span":56.01128969144456,"size":48.01128969144456},{"center":240,"start":212.01149754874206,"span":56.32409377565676,"size":48.32409377565676},{"center":296,"start":268.3355913243988,"span":59.42266840803292,"size":51.42266840803292}]}
{"name":"E_zero","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":400,"sectionBoundary":[],"strength":0,"size":48,"baseLength":336,"length":336,"divider":-1,"dividers":[],"overflow":false,"slots":[{"center":40,"start":12,"span":56,"size":48},{"center":96,"start":68,"span":56,"size":48},{"center":140,"start":124,"span":32,"size":48},{"center":184,"start":156,"span":56,"size":48},{"center":240,"start":212,"span":56,"size":48},{"center":296,"start":268,"span":56,"size":48}]}
{"name":"F_crowded","kinds":["app","app","app","app","small-spacer","app","app","app"],"preferredSize":48,"available":200,"magnification":2,"sectionSpacing":20,"pointer":100,"sectionBoundary":[4],"strength":1,"size":32,"baseLength":356,"length":433.29553239087716,"divider":262.92817455493025,"dividers":[262.92817455493025],"overflow":true,"slots":[{"center":32,"start":12,"span":47.54387444978764,"size":39.54387444978764},{"center":72,"start":59.54387444978764,"span":65.04654522373978,"size":57.046545223739784},{"center":112,"start":124.59041967352742,"span":70.5919194186592,"size":62.5919194186592},{"center":152,"start":195.18233909218662,"span":53.74583546274365,"size":45.74583546274365},{"center":212,"start":276.92817455493025,"span":24.317457515909926,"size":32.63491503181985},{"center":244,"start":301.2456320708402,"span":40.049081941738386,"size":32.049081941738386},{"center":284,"start":341.2947140125786,"span":40.000813419088516,"size":32.000813419088516},{"center":324,"start":381.2955274316671,"span":40.00000495921003,"size":32.00000495921003}]}
{"name":"G_mag3","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":3,"sectionSpacing":16,"pointer":400,"sectionBoundary":[],"strength":1,"size":48,"baseLength":336,"length":345.3956493310794,"divider":-1,"dividers":[],"overflow":false,"slots":[{"center":40,"start":12,"span":56.00000005096818,"size":48.00000005096818},{"center":96,"start":68.00000005096818,"span":56.00001914454256,"size":48.00001914454256},{"center":140,"start":124.00001919551075,"span":32.000500447733046,"size":48.00100089546609},{"center":184,"start":156.0005196432438,"span":56.028224228611414,"size":48.028224228611414},{"center":240,"start":212.0287438718552,"span":56.81023443914191,"size":48.81023443914191},{"center":296,"start":268.8389783109971,"span":64.5566710200823,"size":56.556671020082305}]}
{"name":"G_mag0","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":0,"sectionSpacing":16,"pointer":400,"sectionBoundary":[],"strength":1,"size":48,"baseLength":336,"length":336,"divider":-1,"dividers":[],"overflow":false,"slots":[{"center":40,"start":12,"span":56,"size":48},{"center":96,"start":68,"span":56,"size":48},{"center":140,"start":124,"span":32,"size":48},{"center":184,"start":156,"span":56,"size":48},{"center":240,"start":212,"span":56,"size":48},{"center":296,"start":268,"span":56,"size":48}]}
{"name":"H_str2","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":400,"sectionBoundary":[],"strength":2.5,"size":48,"baseLength":336,"length":343.51651946486356,"divider":-1,"dividers":[],"overflow":false,"slots":[{"center":40,"start":12,"span":56.00000004077454,"size":48.00000004077454},{"center":96,"start":68.00000004077454,"span":56.00001531563405,"size":48.00001531563405},{"center":140,"start":124.0000153564086,"span":32.00040035818644,"size":48.00080071637288},{"center":184,"start":156.00041571459502,"span":56.022579382889134,"size":48.022579382889134},{"center":240,"start":212.02299509748417,"span":56.648187551313534,"size":48.648187551313534},{"center":296,"start":268.6711826487977,"span":62.84533681606584,"size":54.84533681606584}]}
{"name":"H_strneg","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":400,"sectionBoundary":[],"strength":-0.5,"size":48,"baseLength":336,"length":336,"divider":-1,"dividers":[],"overflow":false,"slots":[{"center":40,"start":12,"span":56,"size":48},{"center":96,"start":68,"span":56,"size":48},{"center":140,"start":124,"span":32,"size":48},{"center":184,"start":156,"span":56,"size":48},{"center":240,"start":212,"span":56,"size":48},{"center":296,"start":268,"span":56,"size":48}]}
{"name":"I_bnd","kinds":["app","app","app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":400,"sectionBoundary":[2,2,0,8,5,99],"strength":1,"size":48,"baseLength":496,"length":583.075340080127,"divider":306.09378541419676,"dividers":[136.0000153564086,306.09378541419676],"overflow":false,"slots":[{"center":40,"start":12,"span":56.00000004077454,"size":48.00000004077454},{"center":96,"start":68.00000004077454,"span":56.00001531563405,"size":48.00001531563405},{"center":176,"start":148.0000153564086,"span":56.012881764911455,"size":48.012881764911455},{"center":232,"start":204.01289712132007,"span":56.426585467068506,"size":48.426585467068506},{"center":276,"start":260.43948258838856,"span":33.6543028258082,"size":51.3086056516164},{"center":344,"start":318.09378541419676,"span":79.29077733296512,"size":71.29077733296512},{"center":400,"start":397.3845627471619,"span":94.4,"size":86.4},{"center":456,"start":491.7845627471619,"span":79.29077733296512,"size":71.29077733296512}]}
{"name":"J_scalar","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":400,"sectionBoundary":3,"strength":1,"size":48,"baseLength":360,"length":375.96109031437084,"divider":168.00041571459502,"dividers":[168.00041571459502],"overflow":false,"slots":[{"center":40,"start":12,"span":56.00000004077454,"size":48.00000004077454},{"center":96,"start":68.00000004077454,"span":56.00001531563405,"size":48.00001531563405},{"center":140,"start":124.0000153564086,"span":32.00040035818644,"size":48.00080071637288},{"center":208,"start":180.00041571459502,"span":56.10758290053819,"size":48.10758290053819},{"center":264,"start":236.10799861513323,"span":58.011896617081305,"size":50.011896617081305},{"center":320,"start":294.1198952322145,"span":69.84119508215633,"size":61.84119508215633}]}
{"name":"K_empty","kinds":[],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":400,"sectionBoundary":[],"strength":1,"size":48,"baseLength":24,"length":24,"divider":-1,"dividers":[],"overflow":false,"slots":[]}
{"name":"L_left","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":0,"sectionBoundary":[],"strength":1,"size":48,"baseLength":336,"length":375.60965999990214,"divider":-1,"dividers":[],"overflow":false,"slots":[{"center":40,"start":12,"span":85.75375726911678,"size":77.75375726911678},{"center":96,"start":97.75375726911678,"span":64.83454588136226,"size":56.83454588136227},{"center":140,"start":162.58830315047902,"span":32.84358912556942,"size":49.687178251138846},{"center":184,"start":195.43189227604844,"span":56.17379102208385,"size":48.17379102208385},{"center":240,"start":251.6056832981323,"span":56.0039437784814,"size":48.0039437784814},{"center":296,"start":307.6096270766137,"span":56.00003292328844,"size":48.00003292328844}]}
{"name":"M_right","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":48,"available":800,"magnification":1.8,"sectionSpacing":16,"pointer":800,"sectionBoundary":[],"strength":1,"size":48,"baseLength":336,"length":336,"divider":-1,"dividers":[],"overflow":false,"slots":[{"center":40,"start":12,"span":56,"size":48},{"center":96,"start":68,"span":56,"size":48},{"center":140,"start":124,"span":32,"size":48},{"center":184,"start":156,"span":56,"size":48},{"center":240,"start":212,"span":56,"size":48},{"center":296,"start":268,"span":56,"size":48}]}
{"name":"N_pref","kinds":["app","app","small-spacer","app","app","app"],"preferredSize":36,"available":800,"magnification":1.5,"sectionSpacing":12,"pointer":400,"sectionBoundary":[3],"strength":1,"size":36,"baseLength":290,"length":290.08697965522987,"divider":136.00000000523627,"dividers":[136.00000000523627],"overflow":false,"slots":[{"center":34,"start":12,"span":44.000000000000014,"size":36.000000000000014},{"center":78,"start":56.000000000000014,"span":44.00000000004225,"size":36.00000000004225},{"center":113,"start":100.00000000004226,"span":26.000000005194003,"size":36.00000001038801},{"center":168,"start":146.00000000523627,"span":44.00001652799929,"size":36.00001652799929},{"center":212,"start":190.00001653323557,"span":44.00195429177295,"size":36.00195429177295},{"center":256,"start":234.00197082500853,"span":44.08500883022136,"size":36.08500883022136}]}
''';

const _tolerance = 1e-9;

/// Scenarios whose `pointer: null` in JSON actually means a non-finite value.
double _pointer(Map<String, dynamic> scenario) {
  final pointer = scenario['pointer'];
  if (pointer != null) return (pointer as num).toDouble();
  return switch (scenario['name'] as String) {
    'C_nan' => double.nan,
    'D_inf' => double.infinity,
    _ => throw ArgumentError('null pointer for ${scenario['name']}'),
  };
}

List<int> _boundary(Map<String, dynamic> scenario) {
  final value = scenario['sectionBoundary'];
  if (value is List) return value.cast<int>();
  return <int>[value as int];
}

DockLayoutResult _run(Map<String, dynamic> scenario) => layout(
      kinds: (scenario['kinds'] as List).cast<String>(),
      preferredSize: (scenario['preferredSize'] as num).toDouble(),
      available: (scenario['available'] as num).toDouble(),
      magnification: (scenario['magnification'] as num).toDouble(),
      sectionSpacing: (scenario['sectionSpacing'] as num).toDouble(),
      pointer: _pointer(scenario),
      sectionBoundary: _boundary(scenario),
      strength: (scenario['strength'] as num).toDouble(),
    );

void _expectClose(double actual, Object? expected, String what) {
  expect(actual, closeTo((expected! as num).toDouble(), _tolerance),
      reason: what);
}

void _checkScenario(Map<String, dynamic> scenario) {
  final name = scenario['name'] as String;
  final result = _run(scenario);
  _expectClose(result.size, scenario['size'], '$name.size');
  _expectClose(result.baseLength, scenario['baseLength'], '$name.baseLength');
  _expectClose(result.length, scenario['length'], '$name.length');
  _expectClose(result.divider, scenario['divider'], '$name.divider');
  expect(result.overflow, scenario['overflow'], reason: '$name.overflow');
  final expectedDividers = (scenario['dividers'] as List).cast<num>();
  expect(result.dividers, hasLength(expectedDividers.length),
      reason: '$name.dividers.length');
  for (var i = 0; i < expectedDividers.length; i++) {
    _expectClose(result.dividers[i], expectedDividers[i], '$name.dividers[$i]');
  }
  final expectedSlots = (scenario['slots'] as List).cast<Map<String, dynamic>>();
  expect(result.slots, hasLength(expectedSlots.length),
      reason: '$name.slots.length');
  for (var i = 0; i < expectedSlots.length; i++) {
    final slot = result.slots[i];
    final expected = expectedSlots[i];
    _expectClose(slot.center, expected['center'], '$name.slots[$i].center');
    _expectClose(slot.start, expected['start'], '$name.slots[$i].start');
    _expectClose(slot.span, expected['span'], '$name.slots[$i].span');
    _expectClose(slot.size, expected['size'], '$name.slots[$i].size');
  }
}

// ---- reconcile() test doubles ------------------------------------------------

/// Minimal `ListModel` analogue recording the op sequence so tests can assert
/// minimality, while mutating a plain `List<Map>` backing store.
final class _ListModel implements DockReconcileModel<Map<String, Object?>> {
  _ListModel(List<Map<String, Object?>> initial)
      : entries = List.of(initial, growable: true);

  final List<Map<String, Object?>> entries;
  final List<String> ops = <String>[];

  @override
  int get count => entries.length;

  @override
  Map<String, Object?> get(int index) => entries[index];

  @override
  void remove(int index) {
    ops.add('remove($index:${entries[index]['key']})');
    entries.removeAt(index);
  }

  @override
  void insert(int index, Map<String, Object?> row) {
    ops.add('insert($index:${row['key']})');
    entries.insert(index, row);
  }

  @override
  void move(int from, int to) {
    ops.add('move($from,$to)');
    entries.insert(to, entries.removeAt(from));
  }

  @override
  void setProperty(int index, String role, Object? value) {
    ops.add('set($index,$role,${entries[index]['key']}=$value)');
    entries[index][role] = value;
  }

  List<String> get keys => [for (final entry in entries) entry['key']! as String];
}

Map<String, Object?> _row(String key, [Object? label]) =>
    <String, Object?>{'key': key, 'label': label ?? key};

void _reconcile(_ListModel model, List<Map<String, Object?>> rows) =>
    reconcile<Map<String, Object?>>(
      model,
      rows,
      keyOf: (entry) => entry['key'],
      rolesOf: (row) => row.keys,
      roleOf: (entry, role) => entry[role],
    );

void main() {
  group('layout() golden values (Node DockLayout.js:18-58)', () {
    final scenarios = [
      for (final line in _truthsJsonl.split('\n'))
        if (line.trim().isNotEmpty)
          jsonDecode(line) as Map<String, dynamic>,
    ];
    for (final scenario in scenarios) {
      if (scenario['name'] == 'B') continue; // deprecated placeholder row
      test('${scenario['name']}', () => _checkScenario(scenario));
    }
  });

  group('amplitude envelope semantics', () {
    const kinds = ['app', 'app', 'small-spacer', 'app', 'app', 'app'];

    test('A=0 collapses every scale to 1', () {
      final result = layout(
        kinds: kinds,
        preferredSize: 48,
        available: 800,
        magnification: 1.8,
        sectionSpacing: 16,
        pointer: 400,
        strength: 0,
      );
      expect(result.length, result.baseLength);
      for (var i = 0; i < kinds.length; i++) {
        final weight = kinds[i] == 'small-spacer' ? 0.5 : 1.0;
        expect(result.slots[i].size, closeTo(result.size, _tolerance));
        expect(result.slots[i].span,
            closeTo(result.size * weight + 8, _tolerance));
      }
    });

    test('A=1 reaches the full source-formula amplitude', () {
      // pointer exactly on slot 0's base center (40) → d=0, exp(0)=1,
      // scale = 1 + 1*(1.8-1) = 1.8 → size 48*1.8 = 86.4, span 94.4.
      final result = layout(
        kinds: kinds,
        preferredSize: 48,
        available: 800,
        magnification: 1.8,
        sectionSpacing: 16,
        pointer: 40,
        strength: 1,
      );
      expect(result.slots[0].size, closeTo(86.4, _tolerance));
      expect(result.slots[0].span, closeTo(94.4, _tolerance));
    });

    test('Gaussian falloff matches 1 + A*(M-1)*exp(-d²/2)', () {
      const pointer = 152.0;
      final result = layout(
        kinds: kinds,
        preferredSize: 48,
        available: 800,
        magnification: 1.8,
        sectionSpacing: 16,
        pointer: pointer,
        strength: 1,
      );
      for (final slot in result.slots) {
        final d = (pointer - slot.center) / (result.size + 8);
        final expectedScale = 1 + 0.8 * math.exp(-d * d / 2);
        expect(slot.size, closeTo(result.size * expectedScale, _tolerance));
      }
    });

    test('pure function: identical inputs give identical outputs', () {
      DockLayoutResult run() => layout(
            kinds: kinds,
            preferredSize: 48,
            available: 800,
            magnification: 1.8,
            sectionSpacing: 16,
            pointer: 96,
            sectionBoundary: const [3],
            strength: 0.7,
          );
      final first = run();
      final second = run();
      expect(second.length, first.length);
      for (var i = 0; i < first.slots.length; i++) {
        expect(second.slots[i].start, first.slots[i].start);
        expect(second.slots[i].span, first.slots[i].span);
      }
    });
  });

  group('reconcile() (DockModel.js:226-243)', () {
    test('removes unwanted entries back-to-front', () {
      final model = _ListModel([_row('a'), _row('b'), _row('c'), _row('d')]);
      _reconcile(model, [_row('a'), _row('c')]);
      expect(model.keys, ['a', 'c']);
      expect(model.ops, ['remove(3:d)', 'remove(1:b)']);
    });

    test('inserts missing rows in place', () {
      final model = _ListModel([_row('a'), _row('c')]);
      _reconcile(model, [_row('a'), _row('b'), _row('c')]);
      expect(model.keys, ['a', 'b', 'c']);
      expect(model.ops, ['insert(1:b)']);
    });

    test('moves a later entry forward to its slot', () {
      final model = _ListModel([_row('a'), _row('b'), _row('c')]);
      _reconcile(model, [_row('c'), _row('a'), _row('b')]);
      expect(model.keys, ['c', 'a', 'b']);
      expect(model.ops, ['move(2,0)']);
    });

    test('updates roles on a kept entry without structural ops', () {
      final model = _ListModel([_row('a', 'old')]);
      _reconcile(model, [_row('a', 'new')]);
      expect(model.keys, ['a']);
      expect(model.entries[0]['label'], 'new');
      expect(model.ops, ['set(0,label,a=new)']);
    });

    test('mixed remove+move+insert+update keeps delegate identity', () {
      final kept = _row('a', 'old');
      final model = _ListModel([kept, _row('b'), _row('c'), _row('d')]);
      _reconcile(model, [_row('d'), _row('a', 'new'), _row('e')]);
      expect(model.keys, ['d', 'a', 'e']);
      expect(
        model.ops,
        [
          'remove(2:c)',
          'remove(1:b)',
          'move(1,0)',
          'set(1,label,a=new)',
          'insert(2:e)',
        ],
      );
      // Identity preserved: the same entry object was moved and patched.
      expect(identical(model.entries[1], kept), isTrue);
    });

    test('identical lists produce no ops', () {
      final model = _ListModel([_row('a'), _row('b')]);
      _reconcile(model, [_row('a'), _row('b')]);
      expect(model.ops, isEmpty);
    });
  });
}
