// Golden-value tests for the DockLayout.js `folderFan` port
// (plugins/kos_dock/lib/src/widgets/folder_fan_math.dart).
//
// The truth table below was generated by evaluating the verbatim
// DockLayout.js:125-256 functions under Node (fan_truths.jsonl, 22
// scenarios — same gen_truths.js method as dock_magnifier_test.dart).
// `maximumOutset: null` in JSON is Infinity (JSON has no Inf literal).
// Every scenario asserts the full geometry record plus each `slots[]`
// entry and the trailing `slot(count)` action tile rect.

import 'dart:convert';
import 'dart:math' as math;

import 'package:kos_dock/src/widgets/folder_fan_math.dart';
import 'package:test/test.dart';

const _truthsJsonl = r'''
{"name":"B5","edge":"bottom","count":5,"maxW":600,"maxH":800,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":429,"height":529,"count":5,"step":76,"header":149,"stackReserve":0,"iconSize":64,"iconInset":88.7196563615247,"tileWidth":370,"tileHeight":72,"originX":340.2803436384753,"originY":485,"outset":null,"padding":null,"distance":null,"angle":0.19198621771937624,"radius":1979.308746815571},"slots":[{"x":8.280343638475301,"y":449,"width":370,"height":72,"rotation":0},{"x":9.739259634067082,"y":373.0186737019855,"width":370,"height":72,"rotation":2.2},{"x":14.113856934764783,"y":297.149356581398,"width":370,"height":72,"rotation":4.4},{"x":21.397686652807636,"y":221.50389269541154,"width":370,"height":72,"rotation":6.6},{"x":31.580011205489825,"y":146.19379610410851,"width":370,"height":72,"rotation":8.8}],"actionSlot":{"x":44.64582014415191,"y":71.33008648011298,"width":370,"height":72,"rotation":10.999999999999998}}
{"name":"B5r","edge":"bottom","count":5,"maxW":600,"maxH":800,"labelsLeft":false,"iconSize":64,"maximumOutset":null,"geometry":{"width":429,"height":529,"count":5,"step":76,"header":149,"stackReserve":0,"iconSize":64,"iconInset":88.7196563615247,"tileWidth":370,"tileHeight":72,"originX":340.2803436384753,"originY":485,"outset":null,"padding":null,"distance":null,"angle":0.19198621771937624,"radius":1979.308746815571},"slots":[{"x":50.7196563615247,"y":449,"width":370,"height":72,"rotation":0},{"x":49.26074036593292,"y":373.0186737019855,"width":370,"height":72,"rotation":-2.2},{"x":44.88614306523522,"y":297.149356581398,"width":370,"height":72,"rotation":-4.4},{"x":37.602313347192364,"y":221.50389269541154,"width":370,"height":72,"rotation":-6.6},{"x":27.419988794510175,"y":146.19379610410851,"width":370,"height":72,"rotation":-8.8}],"actionSlot":{"x":14.354179855848088,"y":71.33008648011298,"width":370,"height":72,"rotation":-10.999999999999998}}
{"name":"B1","edge":"bottom","count":1,"maxW":600,"maxH":800,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":396,"height":205,"count":1,"step":76,"header":129,"stackReserve":0,"iconSize":64,"iconInset":55.32104504549437,"tileWidth":370,"tileHeight":72,"originX":340.6789549545056,"originY":161,"outset":null,"padding":null,"distance":null,"angle":0.12217304763960307,"radius":622.0684632848937},"slots":[{"x":8.678954954505627,"y":125,"width":370,"height":72,"rotation":0}],"actionSlot":{"x":13.315758948547114,"y":49.1889248264209,"width":370,"height":72,"rotation":7.000000000000001}}
{"name":"B0","edge":"bottom","count":0,"maxW":600,"maxH":800,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":386,"height":88,"count":0,"step":76,"header":88,"stackReserve":0,"iconSize":64,"iconInset":46,"tileWidth":370,"tileHeight":72,"originX":340,"originY":44,"outset":null,"padding":null,"distance":null,"angle":0,"radius":0},"slots":[],"actionSlot":{"x":8,"y":8,"width":370,"height":72,"rotation":0}}
{"name":"B12","edge":"bottom","count":12,"maxW":600,"maxH":800,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":432,"height":553,"count":5,"step":76,"header":173,"stackReserve":24,"iconSize":64,"iconInset":91.73403935493769,"tileWidth":370,"tileHeight":72,"originX":340.2659606450623,"originY":509,"outset":null,"padding":null,"distance":null,"angle":0.19198621771937624,"radius":2104.31772029866},"slots":[{"x":8.265960645062307,"y":473,"width":370,"height":72,"rotation":0},{"x":9.638227800680909,"y":397.01652108544835,"width":370,"height":72,"rotation":2.0693069306930694},{"x":13.753239502495148,"y":321.13214282616207,"width":370,"height":72,"rotation":4.138613861386139},{"x":20.605628789661694,"y":245.44583662641662,"width":370,"height":72,"rotation":6.207920792079208},{"x":30.186458505337782,"y":170.05631555708152,"width":370,"height":72,"rotation":8.277227722772277}],"actionSlot":{"x":46.92820408793955,"y":71.4772498367517,"width":370,"height":72,"rotation":10.999999999999998}}
{"name":"B8","edge":"bottom","count":8,"maxW":600,"maxH":800,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":432,"height":553,"count":5,"step":76,"header":173,"stackReserve":24,"iconSize":64,"iconInset":91.73403935493769,"tileWidth":370,"tileHeight":72,"originX":340.2659606450623,"originY":509,"outset":null,"padding":null,"distance":null,"angle":0.19198621771937624,"radius":2104.31772029866},"slots":[{"x":8.265960645062307,"y":473,"width":370,"height":72,"rotation":0},{"x":9.638227800680909,"y":397.01652108544835,"width":370,"height":72,"rotation":2.0693069306930694},{"x":13.753239502495148,"y":321.13214282616207,"width":370,"height":72,"rotation":4.138613861386139},{"x":20.605628789661694,"y":245.44583662641662,"width":370,"height":72,"rotation":6.207920792079208},{"x":30.186458505337782,"y":170.05631555708152,"width":370,"height":72,"rotation":8.277227722772277}],"actionSlot":{"x":46.92820408793955,"y":71.4772498367517,"width":370,"height":72,"rotation":10.999999999999998}}
{"name":"B5_out120","edge":"bottom","count":5,"maxW":600,"maxH":800,"labelsLeft":true,"iconSize":64,"maximumOutset":120,"geometry":{"width":429,"height":529,"count":5,"step":76,"header":149,"stackReserve":0,"iconSize":64,"iconInset":88.71966002433703,"tileWidth":370,"tileHeight":72,"originX":340.28033997566297,"originY":485,"outset":null,"padding":null,"distance":null,"angle":0.19198328824217714,"radius":1979.3389491310793},"slots":[{"x":8.280339975662969,"y":449,"width":370,"height":72,"rotation":0},{"x":9.739233715433443,"y":373.0186731321557,"width":370,"height":72,"rotation":2.1999664306640625},{"x":14.113764347100243,"y":297.1493520247757,"width":370,"height":72,"rotation":4.399932861328125},{"x":21.397483277959793,"y":221.50387732814636,"width":370,"height":72,"rotation":6.5998992919921875},{"x":31.579653416261976,"y":146.1937597155918,"width":370,"height":72,"rotation":8.79986572265625}],"actionSlot":{"x":44.64526499899631,"y":71.3300155031144,"width":370,"height":72,"rotation":10.99983215332031}}
{"name":"B5_out90","edge":"bottom","count":5,"maxW":600,"maxH":800,"labelsLeft":true,"iconSize":64,"maximumOutset":90,"geometry":{"width":429,"height":529,"count":5,"step":76,"header":149,"stackReserve":0,"iconSize":64,"iconInset":88.71966002433703,"tileWidth":370,"tileHeight":72,"originX":340.28033997566297,"originY":485,"outset":null,"padding":null,"distance":null,"angle":0.19198328824217714,"radius":1979.3389491310793},"slots":[{"x":8.280339975662969,"y":449,"width":370,"height":72,"rotation":0},{"x":9.739233715433443,"y":373.0186731321557,"width":370,"height":72,"rotation":2.1999664306640625},{"x":14.113764347100243,"y":297.1493520247757,"width":370,"height":72,"rotation":4.399932861328125},{"x":21.397483277959793,"y":221.50387732814636,"width":370,"height":72,"rotation":6.5998992919921875},{"x":31.579653416261976,"y":146.1937597155918,"width":370,"height":72,"rotation":8.79986572265625}],"actionSlot":{"x":44.64526499899631,"y":71.3300155031144,"width":370,"height":72,"rotation":10.99983215332031}}
{"name":"B5_w300","edge":"bottom","count":5,"maxW":300,"maxH":800,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":298,"height":504,"count":5,"step":76,"header":124,"stackReserve":0,"iconSize":64,"iconInset":88.93058485841411,"tileWidth":238.77219873201824,"tileHeight":72,"originX":209.0694151415859,"originY":460,"outset":null,"padding":null,"distance":null,"angle":0.19198621771937624,"radius":1979.308746815571},"slots":[{"x":8.297216409567653,"y":424,"width":238.77219873201824,"height":72,"rotation":0},{"x":9.756132405159434,"y":348.0186737019855,"width":238.77219873201824,"height":72,"rotation":2.2},{"x":14.130729705857135,"y":272.149356581398,"width":238.77219873201824,"height":72,"rotation":4.4},{"x":21.414559423900016,"y":196.5038926954115,"width":238.77219873201824,"height":72,"rotation":6.6},{"x":31.596883976582177,"y":121.19379610410851,"width":238.77219873201824,"height":72,"rotation":8.8}],"actionSlot":{"x":44.662692915244236,"y":46.33008648011298,"width":238.77219873201824,"height":72,"rotation":10.999999999999998}}
{"name":"B5_w160","edge":"bottom","count":5,"maxW":160,"maxH":800,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":156,"height":477,"count":5,"step":76,"header":97,"stackReserve":0,"iconSize":64,"iconInset":89.53012042206959,"tileWidth":96.15186143828828,"tileHeight":72,"originX":66.46987957793041,"originY":433,"outset":null,"padding":null,"distance":null,"angle":0.19198621771937624,"radius":1979.308746815571},"slots":[{"x":8.318018139642135,"y":397,"width":96.15186143828828,"height":72,"rotation":0},{"x":9.776934135233915,"y":321.0186737019855,"width":96.15186143828828,"height":72,"rotation":2.2},{"x":14.151531435931602,"y":245.14935658139802,"width":96.15186143828828,"height":72,"rotation":4.4},{"x":21.435361153974497,"y":169.5038926954115,"width":96.15186143828828,"height":72,"rotation":6.6},{"x":31.617685706656673,"y":94.19379610410851,"width":96.15186143828828,"height":72,"rotation":8.8}],"actionSlot":{"x":44.68349464531873,"y":19.330086480112982,"width":96.15186143828828,"height":72,"rotation":10.999999999999998}}
{"name":"B6_h200","edge":"bottom","count":6,"maxW":600,"maxH":200,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":386,"height":88,"count":0,"step":76,"header":88,"stackReserve":0,"iconSize":64,"iconInset":46,"tileWidth":370,"tileHeight":72,"originX":340,"originY":44,"outset":null,"padding":null,"distance":null,"angle":0,"radius":0},"slots":[],"actionSlot":{"x":8,"y":8,"width":370,"height":72,"rotation":0}}
{"name":"B6_h150","edge":"bottom","count":6,"maxW":600,"maxH":150,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":386,"height":88,"count":0,"step":76,"header":88,"stackReserve":0,"iconSize":64,"iconInset":46,"tileWidth":370,"tileHeight":72,"originX":340,"originY":44,"outset":null,"padding":null,"distance":null,"angle":0,"radius":0},"slots":[],"actionSlot":{"x":8,"y":8,"width":370,"height":72,"rotation":0}}
{"name":"B5_i40","edge":"bottom","count":5,"maxW":600,"maxH":800,"labelsLeft":true,"iconSize":40,"maximumOutset":null,"geometry":{"width":429,"height":529,"count":5,"step":76,"header":149,"stackReserve":0,"iconSize":64,"iconInset":88.7196563615247,"tileWidth":370,"tileHeight":72,"originX":340.2803436384753,"originY":485,"outset":null,"padding":null,"distance":null,"angle":0.19198621771937624,"radius":1979.308746815571},"slots":[{"x":8.280343638475301,"y":449,"width":370,"height":72,"rotation":0},{"x":9.739259634067082,"y":373.0186737019855,"width":370,"height":72,"rotation":2.2},{"x":14.113856934764783,"y":297.149356581398,"width":370,"height":72,"rotation":4.4},{"x":21.397686652807636,"y":221.50389269541154,"width":370,"height":72,"rotation":6.6},{"x":31.580011205489825,"y":146.19379610410851,"width":370,"height":72,"rotation":8.8}],"actionSlot":{"x":44.64582014415191,"y":71.33008648011298,"width":370,"height":72,"rotation":10.999999999999998}}
{"name":"B5_i80","edge":"bottom","count":5,"maxW":600,"maxH":800,"labelsLeft":true,"iconSize":80,"maximumOutset":null,"geometry":{"width":516,"height":569,"count":4,"step":92.8,"header":197.8,"stackReserve":24,"iconSize":80,"iconInset":95.63833500119699,"tileWidth":458,"tileHeight":88,"originX":420.361664998803,"originY":517,"outset":null,"padding":null,"distance":null,"angle":0.17453292519943295,"radius":2264.3292063570134},"slots":[{"x":8.361664998803008,"y":473,"width":458,"height":88,"rotation":0},{"x":10.263030454493276,"y":380.225976286678,"width":458,"height":88,"rotation":2.348178137651822},{"x":15.963933654611708,"y":287.60775794245046,"width":458,"height":88,"rotation":4.696356275303644},{"x":25.454800460926947,"y":195.30088867574364,"width":458,"height":88,"rotation":7.044534412955465}],"actionSlot":{"x":42.76191356344975,"y":79.80335967809799,"width":458,"height":88,"rotation":10}}
{"name":"B5_h100","edge":"bottom","count":5,"maxW":600,"maxH":100,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":386,"height":88,"count":0,"step":76,"header":88,"stackReserve":0,"iconSize":64,"iconInset":46,"tileWidth":370,"tileHeight":72,"originX":340,"originY":44,"outset":null,"padding":null,"distance":null,"angle":0,"radius":0},"slots":[],"actionSlot":{"x":8,"y":8,"width":370,"height":72,"rotation":0}}
{"name":"L5","edge":"left","count":5,"maxW":700,"maxH":800,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":632,"height":194,"count":4,"step":112,"header":0,"stackReserve":24,"iconSize":64,"iconInset":80,"tileWidth":100,"tileHeight":102,"originX":null,"originY":null,"outset":32,"padding":30,"distance":472,"angle":null,"radius":null},"slots":[{"x":30,"y":62,"width":100,"height":102,"rotation":0},{"x":142,"y":60.19821890261419,"width":100,"height":102,"rotation":-1.8428366343196325},{"x":254,"y":54.79287561045676,"width":100,"height":102,"rotation":-3.681868327357436},{"x":366,"y":45.78397012352772,"width":100,"height":102,"rotation":-5.513337064819477}],"actionSlot":{"x":502,"y":30,"width":100,"height":102,"rotation":-7.721825800130976}}
{"name":"R5","edge":"right","count":5,"maxW":700,"maxH":800,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":632,"height":194,"count":4,"step":112,"header":0,"stackReserve":24,"iconSize":64,"iconInset":80,"tileWidth":100,"tileHeight":102,"originX":null,"originY":null,"outset":32,"padding":30,"distance":472,"angle":null,"radius":null},"slots":[{"x":502,"y":62,"width":100,"height":102,"rotation":0},{"x":390,"y":60.19821890261419,"width":100,"height":102,"rotation":1.8428366343196325},{"x":278,"y":54.79287561045676,"width":100,"height":102,"rotation":3.681868327357436},{"x":166,"y":45.78397012352772,"width":100,"height":102,"rotation":5.513337064819477}],"actionSlot":{"x":30,"y":30,"width":100,"height":102,"rotation":7.721825800130976}}
{"name":"L12","edge":"left","count":12,"maxW":900,"maxH":800,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":856,"height":194,"count":6,"step":112,"header":0,"stackReserve":24,"iconSize":64,"iconInset":80,"tileWidth":100,"tileHeight":102,"originX":null,"originY":null,"outset":32,"padding":30,"distance":696,"angle":null,"radius":null},"slots":[{"x":30,"y":62,"width":100,"height":102,"rotation":0},{"x":142,"y":61.171356850310474,"width":100,"height":102,"rotation":-0.8477551867426076},{"x":254,"y":58.68542740124191,"width":100,"height":102,"rotation":-1.6951393460720354},{"x":366,"y":54.54221165279429,"width":100,"height":102,"rotation":-2.5417824239523754},{"x":478,"y":48.74170960496763,"width":100,"height":102,"rotation":-3.387316306727036},{"x":590,"y":41.28392125776192,"width":100,"height":102,"rotation":-4.231375775448141}],"actionSlot":{"x":726,"y":30,"width":100,"height":102,"rotation":-5.253802751262255}}
{"name":"L9","edge":"left","count":9,"maxW":900,"maxH":800,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":856,"height":194,"count":6,"step":112,"header":0,"stackReserve":24,"iconSize":64,"iconInset":80,"tileWidth":100,"tileHeight":102,"originX":null,"originY":null,"outset":32,"padding":30,"distance":696,"angle":null,"radius":null},"slots":[{"x":30,"y":62,"width":100,"height":102,"rotation":0},{"x":142,"y":61.171356850310474,"width":100,"height":102,"rotation":-0.8477551867426076},{"x":254,"y":58.68542740124191,"width":100,"height":102,"rotation":-1.6951393460720354},{"x":366,"y":54.54221165279429,"width":100,"height":102,"rotation":-2.5417824239523754},{"x":478,"y":48.74170960496763,"width":100,"height":102,"rotation":-3.387316306727036},{"x":590,"y":41.28392125776192,"width":100,"height":102,"rotation":-4.231375775448141}],"actionSlot":{"x":726,"y":30,"width":100,"height":102,"rotation":-5.253802751262255}}
{"name":"L5_w120","edge":"left","count":5,"maxW":120,"maxH":800,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":120,"height":154.66666666666666,"count":0,"step":74,"header":0,"stackReserve":0,"iconSize":58.666666666666664,"iconInset":60,"tileWidth":62,"tileHeight":96.66666666666666,"originX":null,"originY":null,"outset":0,"padding":29,"distance":0,"angle":null,"radius":null},"slots":[],"actionSlot":{"x":29,"y":29,"width":62,"height":96.66666666666666,"rotation":0}}
{"name":"L0","edge":"left","count":0,"maxW":400,"maxH":800,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":160,"height":162,"count":0,"step":112,"header":0,"stackReserve":0,"iconSize":64,"iconInset":80,"tileWidth":100,"tileHeight":102,"originX":null,"originY":null,"outset":0,"padding":30,"distance":0,"angle":null,"radius":null},"slots":[],"actionSlot":{"x":30,"y":30,"width":100,"height":102,"rotation":0}}
{"name":"R5_h200","edge":"right","count":5,"maxW":400,"maxH":200,"labelsLeft":true,"iconSize":64,"maximumOutset":null,"geometry":{"width":296,"height":173.99023468817563,"count":1,"step":112,"header":0,"stackReserve":24,"iconSize":64,"iconInset":80,"tileWidth":100,"tileHeight":102,"originX":null,"originY":null,"outset":11.990234688175619,"padding":30,"distance":136,"angle":null,"radius":null},"slots":[{"x":166,"y":41.99023468817562,"width":100,"height":102,"rotation":0}],"actionSlot":{"x":30,"y":30,"width":100,"height":102,"rotation":10}}
''';

const _tolerance = 1e-9;

FolderFanEdge _edge(String name) => switch (name) {
  'bottom' => FolderFanEdge.bottom,
  'left' => FolderFanEdge.left,
  'right' => FolderFanEdge.right,
  _ => throw ArgumentError(name),
};

FolderFanGeometry _run(Map<String, dynamic> scenario) => folderFan(
  edge: _edge(scenario['edge'] as String),
  count: scenario['count'] as int,
  maximumWidth: (scenario['maxW'] as num).toDouble(),
  maximumHeight: (scenario['maxH'] as num).toDouble(),
  labelsLeft: scenario['labelsLeft'] as bool,
  requestedIconSize: (scenario['iconSize'] as num).toDouble(),
  maximumOutset: scenario['maximumOutset'] == null
      ? double.infinity
      : (scenario['maximumOutset'] as num).toDouble(),
);

void _expectClose(double? actual, Object? expected, String what) {
  if (expected == null) {
    expect(actual, isNull, reason: what);
    return;
  }
  expect(
    actual,
    isNotNull,
    reason: '$what (expected ${(expected as num).toDouble()})',
  );
  expect(
    actual!,
    closeTo(expected.toDouble(), _tolerance),
    reason: what,
  );
}

void _expectSlot(
  FolderFanSlot slot,
  Map<String, dynamic> expected,
  String what,
) {
  _expectClose(slot.x, expected['x'], '$what.x');
  _expectClose(slot.y, expected['y'], '$what.y');
  _expectClose(slot.width, expected['width'], '$what.width');
  _expectClose(slot.height, expected['height'], '$what.height');
  _expectClose(slot.rotation, expected['rotation'], '$what.rotation');
}

void _checkScenario(Map<String, dynamic> scenario) {
  final name = scenario['name'] as String;
  final geometry = _run(scenario);
  final expected = scenario['geometry'] as Map<String, dynamic>;
  _expectClose(geometry.width, expected['width'], '$name.width');
  _expectClose(geometry.height, expected['height'], '$name.height');
  expect(geometry.count, expected['count'], reason: '$name.count');
  _expectClose(geometry.step, expected['step'], '$name.step');
  _expectClose(geometry.header, expected['header'], '$name.header');
  _expectClose(
    geometry.stackReserve,
    expected['stackReserve'],
    '$name.stackReserve',
  );
  _expectClose(geometry.iconSize, expected['iconSize'], '$name.iconSize');
  _expectClose(
    geometry.iconInset,
    expected['iconInset'],
    '$name.iconInset',
  );
  _expectClose(
    geometry.tileWidth,
    expected['tileWidth'],
    '$name.tileWidth',
  );
  _expectClose(
    geometry.tileHeight,
    expected['tileHeight'],
    '$name.tileHeight',
  );
  _expectClose(geometry.originX, expected['originX'], '$name.originX');
  _expectClose(geometry.originY, expected['originY'], '$name.originY');
  _expectClose(geometry.outset, expected['outset'], '$name.outset');
  _expectClose(geometry.padding, expected['padding'], '$name.padding');
  _expectClose(geometry.distance, expected['distance'], '$name.distance');
  _expectClose(geometry.angle, expected['angle'], '$name.angle');
  _expectClose(geometry.radius, expected['radius'], '$name.radius');
  final expectedSlots =
      (scenario['slots'] as List).cast<Map<String, dynamic>>();
  expect(
    geometry.slots,
    hasLength(expectedSlots.length),
    reason: '$name.slots.length',
  );
  for (var i = 0; i < expectedSlots.length; i++) {
    _expectSlot(geometry.slots[i], expectedSlots[i], '$name.slots[$i]');
  }
  // Action tile = slot(count) (DockFolderFan.qml:146).
  final action = folderFanSlot(
    _edge(scenario['edge'] as String),
    geometry.count.toDouble(),
    geometry,
    scenario['labelsLeft'] as bool,
  );
  _expectSlot(
    action,
    scenario['actionSlot'] as Map<String, dynamic>,
    '$name.actionSlot',
  );
}

void main() {
  group('folderFan golden values (DockLayout.js:125-256 via Node)', () {
    final scenarios =
        const LineSplitter()
            .convert(_truthsJsonl)
            .where((line) => line.trim().isNotEmpty)
            .map((line) => jsonDecode(line) as Map<String, dynamic>);
    for (final scenario in scenarios) {
      test(scenario['name'] as String, () => _checkScenario(scenario));
    }
  });

  group('source-semantics spot checks', () {
    test('bisection satisfies outset <= maximumOutset - 1', () {
      // :158-170 — 16 iterations then geometry.angle = low; verify the
      // resulting outset obeys the constraint for a finite maximumOutset.
      const maximumOutset = 90.0;
      final geometry = folderFan(
        edge: FolderFanEdge.bottom,
        count: 5,
        maximumWidth: 600,
        maximumHeight: 800,
        labelsLeft: true,
        requestedIconSize: 64,
        maximumOutset: maximumOutset,
      );
      final distance =
          geometry.count * geometry.step + geometry.stackReserve;
      final angle = geometry.angle!;
      final outset =
          distance / angle * (1 - math.cos(angle)) +
          (geometry.iconSize / 2 + 6) * math.cos(angle) +
          geometry.tileHeight / 2 * math.sin(angle) +
          8; // padding (:165)
      expect(outset, lessThanOrEqualTo(maximumOutset - 1));
      // Bisected angle is smaller than the un-clamped min(16, 6+5)°.
      expect(angle, lessThan(11 * math.pi / 180));
      expect(angle, greaterThan(0));
    });

    test('infinite maximumOutset skips the bisection (:158 isFinite)', () {
      final geometry = folderFan(
        edge: FolderFanEdge.bottom,
        count: 5,
        maximumWidth: 600,
        maximumHeight: 800,
        labelsLeft: true,
        requestedIconSize: 64,
      );
      // angle = min(16, 6+5)° = 11° (:154).
      expect(
        geometry.angle,
        closeTo(11 * math.pi / 180, _tolerance),
      );
    });

    test('count == 0 degenerates to a single action slot (:91)', () {
      final geometry = folderFan(
        edge: FolderFanEdge.bottom,
        count: 0,
        maximumWidth: 600,
        maximumHeight: 800,
        labelsLeft: true,
        requestedIconSize: 64,
      );
      expect(geometry.count, 0);
      expect(geometry.slots, isEmpty);
      expect(geometry.angle, 0);
      expect(geometry.radius, 0);
      final action = folderFanSlot(
        FolderFanEdge.bottom,
        0,
        geometry,
        true,
      );
      // :236-245 — position 0, no stack reserve, radius 0 → angle 0,
      // y = originY − distance − tileHeight/2.
      expect(action.rotation, 0);
    });

    test('stackReserve is 24 only when entries remain hidden (:153)', () {
      final overflowed = folderFan(
        edge: FolderFanEdge.bottom,
        count: 12,
        maximumWidth: 600,
        maximumHeight: 800,
        labelsLeft: true,
        requestedIconSize: 64,
      );
      expect(overflowed.stackReserve, 24);
      expect(overflowed.count, lessThan(12));
      final fits = folderFan(
        edge: FolderFanEdge.bottom,
        count: 5,
        maximumWidth: 600,
        maximumHeight: 800,
        labelsLeft: true,
        requestedIconSize: 64,
      );
      expect(fits.stackReserve, 0);
    });

    test('iconSize is floored at max(64, round(requested)) (:198)', () {
      final small = folderFan(
        edge: FolderFanEdge.bottom,
        count: 1,
        maximumWidth: 600,
        maximumHeight: 800,
        labelsLeft: true,
        requestedIconSize: 40,
      );
      expect(small.iconSize, 64); // B5_i40 → 64 floor
      final big = folderFan(
        edge: FolderFanEdge.bottom,
        count: 1,
        maximumWidth: 600,
        maximumHeight: 800,
        labelsLeft: true,
        requestedIconSize: 80,
      );
      expect(big.iconSize, 80);
    });
  });
}
